### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by vitr** [Laravel-Backpack/NewsCRUD#3]
I think, this is the same issue, we've got on travis https://travis-ci.org/Laravel-Backpack/NewsCRUD
```
$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - backpack/crud 3.0.0 requires backpack/base ^0.6.7 -> satisfiable by backpack/base[0.6.7].
    - backpack/crud 3.0.1 requires backpack/base ^0.6.7 -> satisfiable by backpack/base[0.6.7].
    - backpack/crud 3.0.2 requires backpack/base ^0.6.7 -> satisfiable by backpack/base[0.6.7].
    - backpack/crud 3.0.3 requires backpack/base ^0.6.7 -> satisfiable by backpack/base[0.6.7].
    - backpack/crud 3.0.4 requires backpack/base ^0.6.7 -> satisfiable by backpack/base[0.6.7].
    - Conclusion: don't install backpack/base 0.6.7
    - Installation request for backpack/crud ^3.0.0 -> satisfiable by backpack/crud[3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4].
```

**Comment by tabacitu** [comment]
Hi @vitr ,

I tried, but I couldn't get the same error. Looks to me like you have an old version of Backpack\Base but a new version of Backpac\NewsCRUD and I don't understand how you got there...

Can you do a ```composer update``` on the project? That should fix it. Please mind that [migrating to CRUD 3.0 might bring up some issues](https://laravel-backpack.readme.io/docs/whats-new-july-2016#what-could-break-if-i-update).

Cheers!

**Comment by vitr** [comment]
hi @tabacitu 
I fixed this with simple `"backpack/crud": "^3.0.5"` in composer, see my pull https://github.com/Laravel-Backpack/NewsCRUD/pull/4
but you've got some other errors on travis, related to phpunit test coverage
cheers,
Vit

**Comment by tabacitu** [comment]
Ok, great to hear that.

Yeah, you're right, thank you. I haven't even begun writing the unit tests - though not a perfect situation, it's normal for them to fail right now, so I stopped paying attention to them. I'll write some bogus ones until then, so that we'll notice at least these type of errors using travis.

Thanks, cheers!

**Comment by tabacitu** [comment]
...apparently travis is still failing. And I have no idea why - it works perfectly on my environment. **Do _you_ have any idea?**

All other packages that depend on Backpack\CRUD are failing in travis too, so I expect it to be a misconfiguration in CRUD's composer.json - but I don't understand why.
- NewsCRUD requires Backpack\CRUD ^3.0.5;
- Backpack\CRUD ^3.0.5 requires Backpack/Base ^0.6.7;
- Which is all fine if you ask me - that version exists, is the latest, and _should_ be usable.

I'm at a loss here...

**Comment by vitr** [comment]
the caret `^` modifier works funny, I guess. 
I fix this in  https://github.com/Laravel-Backpack/NewsCRUD/pull/5

**Comment by tabacitu** [comment]
That works :-) Thanks a lot.

I still don't understand, though... 3.0.5 should be good enough too... It _should_ resolve to an installable set of packages. 

Do we need to update this requirement every time we push an update to CRUD? 'cause that would be a big pain and _there's got_ to be another solution for that.

**Comment by vitr** [comment]
Sebastian seems to have similar problem
https://travis-ci.org/sebastianbergmann/php-code-coverage/jobs/147491418
it's really weird

**Comment by tabacitu** [comment]
I've just pushed some updates in Backpack\Base, checked [travis](https://travis-ci.org/Laravel-Backpack/NewsCRUD) and it looks like the issue is resolved now - it pulls the latest Backpack\Base. I still don't understand why it didn't work, but hey ho - it works now so I'll close the issue.

Regarding the requirements - I don't think we should support PHP 5.3, since Backpack uses the array format in newer versions. Actually, I doubt it even works in PHP 5.3 and travis is setup to test PHP 5.5, 5.6, 7, nightly and HHVM.

I guess the best course of action here is to drop 5.3 support. Don't you agree?

**Comment by vitr** [comment]
yeah, totally, just move everything to 5.5, like Laravel has PHP >= 5.5.9
